name: git push into another repo to deploy to vercel

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex

    strategy:
      matrix:
        repo:
          - owner: OWNER_KCH
            name: REPO_KCH
            token: TOKEN_KCH
            email: EMAIL_KCH
          - owner: OWNER_KHS
            name: REPO_KHS
            token: TOKEN_KHS
            email: EMAIL_KHS
          - owner: OWNER_PJS
            name: REPO_PJS
            token: TOKEN_PJS
            email: EMAIL_PJS
          - owner: OWNER_LSJ
            name: REPO_LSJ
            token: TOKEN_LSJ
            email: EMAIL_LSJ
            
    steps:
      - uses: actions/checkout@v2
      - name: Install mustache (to update the date)
        run: apk add ruby && gem install mustache
      - name: creates output
        run: sh ./build.sh
      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets[matrix.repo.token] }}
        with:
          source-directory: 'output'
          destination-github-username: ${{ secrets[matrix.repo.owner] }}
          destination-repository-name: ${{ secrets[matrix.repo.name] }}
          user-email: ${{ secrets[matrix.repo.email] }}
          commit-message: ${{ github.event.commits[0].message }}
          target-branch: main
      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY